spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portfolly
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DATABASE_ID}
    password: ${DATABASE_PASSWORD}

  profiles:
    include: oauth,mail,jwt,springdoc,jasypt

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create